# 元々使っていたNode.jsのイメージをベースにする
FROM mcr.microsoft.com/devcontainers/typescript-node:4-24-trixie

RUN sudo apt-get update && sudo apt-get install -y \
    libgtk-3-dev \
    libwebkit2gtk-4.1-dev \
    build-essential \
    curl \
    wget \
    file \
    libxdo-dev \
    libssl-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    pkg-config